version: '3.9'

services:

  dtcc-module-dtcc-builder:
    build:
      context: .
      dockerfile: 'Dockerfile'
      target: dev
      args:
        - _uid=${_UID}
        - gid=${GID}
    working_dir: ${WORKING_DIR}
    container_name: dtcc-module-dtcc-builder
    image: dtcc-module-dtcc-builder-image
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ../:${WORKING_DIR}:rw
      - dtcc-modules-shared-data:${SHARED_DATA_DIR}:rw
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE

volumes:
  dtcc-modules-shared-data:

