version: '3.9'

services:

 rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: dtcc-rabbitmq
    restart: unless-stopped
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbit-data:/var/lib/rabbitmq/
        - rabbit-logs:/var/log/rabbitmq
    networks:
        - default
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}


volumes:
  rabbit-data:
  rabbit-logs: